// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OlehOlehNTT.Infrastructure.Data;

#nullable disable

namespace OlehOlehNTT.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240903084816_SeedingDataPertama")]
    partial class SeedingDataPertama
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.19");

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.KategoriProduk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TabelKategoriProduk");
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.Produk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dekripsi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Harga")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("KategoriId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stok")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ukuran")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlGambar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warna")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("TabelProduk");
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.Produk", b =>
                {
                    b.HasOne("OlehOlehNTT.Domain.Entities.KategoriProduk", "Kategori")
                        .WithMany("DaftarProduk")
                        .HasForeignKey("KategoriId");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.KategoriProduk", b =>
                {
                    b.Navigation("DaftarProduk");
                });
#pragma warning restore 612, 618
        }
    }
}
