// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OlehOlehNTT.Infrastructure.Data;

#nullable disable

namespace OlehOlehNTT.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240907114156_PerbaikiConfigurationOrder")]
    partial class PerbaikiConfigurationOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.19");

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NoHP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TabelAppUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2059868c-4560-4a0c-b1e0-0f820daf65c1"),
                            Alamat = "DI BUMI",
                            Email = "aditaklal@gmail.com",
                            Nama = "Adi Juanito Taklal",
                            NoHP = "081234567890",
                            PasswordHash = "AQAAAAIAAYagAAAAEANLwcgnPskEgQTrGIriPeeXIzl4GKgaYKwg0Qbc33XLRVwhINIf6AgV/TdGiy8svw=="
                        });
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.DetailOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Jumlah")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProdukId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProdukId");

                    b.ToTable("TabelDetailOrder");
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.KategoriProduk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TabelKategoriProduk");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b3fca97-0411-4c97-89c4-286b296b5ea3"),
                            AddedAt = new DateTime(2024, 9, 7, 19, 41, 56, 426, DateTimeKind.Local).AddTicks(670),
                            Nama = "Makanan"
                        });
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.Kurir", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EstimasiWaktu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("OngkosKirim")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TabelKurir");
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.MetodePembayaran", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TabelMetodePembayaran");
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KurirId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MetodePembayaranId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("KurirId");

                    b.HasIndex("MetodePembayaranId");

                    b.ToTable("TabelOrder");
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.Produk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Berat")
                        .HasColumnType("REAL");

                    b.Property<string>("Dekripsi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Harga")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("KategoriId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stok")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ukuran")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlGambar")
                        .HasColumnType("TEXT");

                    b.Property<string>("Warna")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("TabelProduk");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57af9c5d-51ee-4c71-bdd8-0f36d55132b7"),
                            AddedAt = new DateTime(2024, 9, 7, 19, 41, 56, 426, DateTimeKind.Local).AddTicks(1092),
                            Berat = 1000.0,
                            Dekripsi = "Paling enak makan dengan nasi",
                            Harga = 50000.0,
                            Nama = "Se'i Babi",
                            Stok = 100
                        });
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.DetailOrder", b =>
                {
                    b.HasOne("OlehOlehNTT.Domain.Entities.Order", "Order")
                        .WithMany("DaftarDetailOrder")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlehOlehNTT.Domain.Entities.Produk", "Produk")
                        .WithMany()
                        .HasForeignKey("ProdukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Produk");
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.Order", b =>
                {
                    b.HasOne("OlehOlehNTT.Domain.Entities.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlehOlehNTT.Domain.Entities.Kurir", "Kurir")
                        .WithMany()
                        .HasForeignKey("KurirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OlehOlehNTT.Domain.Entities.MetodePembayaran", "MetodePembayaran")
                        .WithMany()
                        .HasForeignKey("MetodePembayaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Kurir");

                    b.Navigation("MetodePembayaran");
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.Produk", b =>
                {
                    b.HasOne("OlehOlehNTT.Domain.Entities.KategoriProduk", "Kategori")
                        .WithMany("DaftarProduk")
                        .HasForeignKey("KategoriId");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.KategoriProduk", b =>
                {
                    b.Navigation("DaftarProduk");
                });

            modelBuilder.Entity("OlehOlehNTT.Domain.Entities.Order", b =>
                {
                    b.Navigation("DaftarDetailOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
